services:

  postgres:
    image: postgres:17-alpine
    container_name: learndevopswithus-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - learndevops-network


  backend:
    image: learndevopswithus-backend:v1
    container_name: learndevopswithus-backend

    environment:
      PORT: 5100

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "5100:5100"

    networks:
      - learndevops-network


  frontend:
    image: learndevopswithus-frontend:v1
    container_name: learndevopswithus-frontend

    depends_on:
      - backend

    ports:
      - "8080:80"

    networks:
      - learndevops-network


volumes:
  postgres_data:


networks:
  learndevops-network:
    driver: bridge
