name: LearnDevopswithUsman DevSecOps

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # =========================================================
  # CI - GATES 1-4
  # =========================================================
  ci:
    name: Gates 1-4 - CI Security
    uses: ./.github/workflows/ci.yml

  # =========================================================
  # BUILD - GATES 5-7
  # =========================================================
  build:
    name: Gates 5-7 - Build Security Publish
    needs: ci
    uses: ./.github/workflows/build.yml
    secrets: inherit
